linters-settings:
  maligned:
    suggest-new: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - maligned
        - goerr113
    - path: internal/server/
      linters:
        - dupl
    - path: internal/configuration/
      linters:
        - dupl
    - path: internal/constants/
      linters:
        - dupl
    - text: "exported: exported var Err*"
      linters:
        - revive
    - text: "mnd: Magic number: 0644*"
      linters:
        - gomnd
    - text: "mnd: Magic number: 0400*"
      linters:
        - gomnd
linters:
  disable-all: true
  enable:
    # - cyclop
    # - errorlint
    # - wrapcheck
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

run:
  skip-dirs:
    - .devcontainer
    - .github
    - doc
