sudo: required
services:
  - docker
env:
  global:
    - DOCKER_BUILD=qmcgaw/private-internet-access
    - MICROBADGER_CODE=tQFy7AxtSUNANPe6aoVChYdsI_I=
  matrix:
    - name=x86_64
script:
  - docker build .
after_script:
  - "curl -X POST https://hooks.microbadger.com/images/${DOCKER_BUILD}/${MICROBADGER_CODE}"
  