version: '3'
services:
  pia:
    build: https://github.com/qdm12/private-internet-access-docker.git
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    init: true
    ports:
      - 8888:8888/tcp
    command: 
    environment:
      - USER=js89ds7
      - PASSWORD=8fd9s239G
      - ENCRYPTION=strong
      - PROTOCOL=udp
      - REGION=CA Montreal
      - NONROOT=no
      - DOT=on
      - BLOCK_MALICIOUS=on
      - BLOCK_NSA=off
      - UNBLOCK=
      - FIREWALL=on
      - EXTRA_SUBNETS=
      - PROXY=on
      - PROXY_LOG_LEVEL=Critical
      - PROXY_USER=
      - PROXY_PASSWORD=
    restart: always
 